const passageActionTypes = {
  UPDATE_PASSAGE: 'UPDATE_PASSAGE',
  CLEAR_PASSAGE: 'CLEAR_PASSAGE',
  INSERT_VOCABULARY_LIST: 'INSERT_VOCABULARY_LIST',
  UPDATE_VOCABULARY_LIST: 'UPDATE_VOCABULARY_LIST',
  DELETE_VOCABULARY: 'DELETE_VOCABULARY',
  RESET_VOCABULARY_LIST: 'RESET_VOCABULARY_LIST'
};

export default passageActionTypes;
